version: '3'
services:
  videollama:
    build:
      context: .
      dockerfile: Dockerfile
    image: videollama:latest
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    working_dir: /app
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '16g'

